version: "3"
services:
  backend:
    build:
      context: backend
  frontend:
    environment:
      - FORUM_BACKEND_PRIVATE_URL=http://backend:8080
    build:
      context: frontend
    depends_on:
      - backend
  nginx:
    image: nginx:1.17.8-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
