version: "3"
services:
  backend:
    build:
      context: backend
    environment:
      - FRONTEND_REVALIDATE_URL=http://frontend:3000/api/revalidate
    volumes:
      - db:/app/db
  frontend:
    build:
      context: frontend
    environment:
      - FORUM_BACKEND_PRIVATE_URL=http://backend:8080
    depends_on:
      - backend
  nginx:
    image: nginx:1.17.8-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
volumes:
  db:
  pages:
