version: "3"
services:
  backend:
    build:
      context: backend
  frontend:
    environment:
      - FORUM_BACKEND_PRIVATE_URL=http://backend:8080
    build:
      context: frontend
    depends_on:
      - backend
    ports:
      - "80:3000"
