# https://golangci-lint.run/usage/configuration/

linters:
  enable:
    - gofmt
    - lll # line length
    - dupl # tool for code clone detection
    - cyclop # checks that functions do not have too many statements
    - gosec # checks for security issues

linters-settings:
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 30
    package-average: 10.0
