name: Backend Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths: [ "backend/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "backend/**" ]
jobs:

  build:
    name: Build the backend Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build backend --tag forum-backend:$(date +%s)
